### ISSUE TITLE
Migrations missing

### ISSUE THREAD

**Issue by laurentiu-cocos** [BitBagCommerce/SyliusShippingExportPlugin#13]
Shouldn't this plugin have also a migration file ?

I'm having an error on /admin/shipping-exports/ page. Some missing tables.

After a while I've executed doctrine:schema:update --dump-sql and indeed I was missing some tables:
     CREATE TABLE bitbag_shipping_gateway (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, config JSON NOT NULL COMMENT '(DC2Type:json_array)', name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE bitbag_shipping_gateway_method (shipping_gateway_id INT NOT NULL, shipping_method_id INT NOT NULL, INDEX IDX_8606B9CBEF84DE5E (shipping_gateway_id), INDEX IDX_8606B9CB5F7D6850 (shipping_method_id), PRIMARY KEY(shipping_gateway_id, shipping_method_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE bitbag_shipping_export (id INT AUTO_INCREMENT NOT NULL, shipment_id INT DEFAULT NULL, shipping_gateway_id INT DEFAULT NULL, exported_at DATETIME DEFAULT NULL, label_path VARCHAR(255) DEFAULT NULL, state VARCHAR(255) NOT NULL, external_id VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_20E62D9F7BE036FC (shipment_id), INDEX IDX_20E62D9FEF84DE5E (shipping_gateway_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;
     ALTER TABLE bitbag_shipping_gateway_method ADD CONSTRAINT FK_8606B9CBEF84DE5E FOREIGN KEY (shipping_gateway_id) REFERENCES bitbag_shipping_gateway (id);
     ALTER TABLE bitbag_shipping_gateway_method ADD CONSTRAINT FK_8606B9CB5F7D6850 FOREIGN KEY (shipping_method_id) REFERENCES sylius_shipping_method (id);
     ALTER TABLE bitbag_shipping_export ADD CONSTRAINT FK_20E62D9F7BE036FC FOREIGN KEY (shipment_id) REFERENCES sylius_shipment (id);
     ALTER TABLE bitbag_shipping_export ADD CONSTRAINT FK_20E62D9FEF84DE5E FOREIGN KEY (shipping_gateway_id) REFERENCES bitbag_shipping_gateway (id);

**Comment by piotrkardasz** [comment]
Hello @laurentiu-cocos 
In my opinion it shouldn't because in a project you can have a custom naming convention or prefixes. 
Take a look at Doctrine naming strategy https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/namingstrategy.html:
```bash
bin/console debug:config doctrine | grep naming_strategy
```
Bear in mind that each time you generate a migration file the contents of the migration file should be verified.

**Comment by piotrkardasz** [comment]
We recommend using doctrine migrations in the projects by using the following commands:
```bash
bin/console debug:config doctrine:migrations:diff
```

> ⚠️ each time you generate a migration file the contents of the migration file should be verified.

Then migrate migrations using:
```bash
bin/console debug:config doctrine:migrations:migrate
```
