### ISSUE TITLE
Issue with sorting by shipping method

### ISSUE THREAD

**Issue by andriusvo** [BitBagCommerce/SyliusShippingExportPlugin#32]
Hello,

I've found a bug while an admin user wants to sort by `Shipping method` in grid `bitbag_admin_shipping_export`.
In file `grids/bitbag_shipping_export.yml` On line 38 there should be `sotable: shipment.method`

**Comment by senghe** [comment]
Hi @andriusvo, thanks for opening the issue. I'll work on reproducing and fixnig this :ok_hand: and be back when have more details
