### ISSUE TITLE
Export are removed when gateway is removed

### ISSUE THREAD

**Issue by ehibes** [BitBagCommerce/SyliusShippingExportPlugin#45]
Hi,

I created a new gateway for a specific carrier and removed the old one. The shipping export created with the old gateway has been removed.
2 solutions:
Invalidate deletion of the gateway.
Set `gateway_id` to null if the gateway is removed.

**Comment by senghe** [comment]
Hu @ehibes, the fix has been already released. Thanks for your help! :)
