### ISSUE TITLE
Obsolete documentation

### ISSUE THREAD

**Issue by gabiudrescu** [BitBagCommerce/SyliusShippingExportPlugin#7]
[This article](https://bitbag.shop/blog/bitbag-shipping-export-plugin-simple-way-to-control-shipments-in-your-online-store) needs some updates:

`            new \BitBag\ShippingExportPlugin\ShippingExportPlugin(),
`

is actually now

`            new \BitBag\SyliusShippingExportPlugin\BitBagShippingExportPlugin(),
`

same for

`    - { resource: "@ShippingExportPlugin/Resources/config/config.yml" }
`

and 

`    resource: "@ShippingExportPlugin/Resources/config/routing.yml"
`

Also, I think these should be included in the repo, as an installation guideline. With a potential read more on the blog.

**Comment by bitbager** [comment]
Thank you, @gabiudrescu. Now it should be fixed.
